#!/usr/bin/env bash
#
data_file=$1
table_name=$(basename "$data_file" .csv)
csvsql --query "
SELECT
  Isla,
  Intervalo,
  CASE
    WHEN MAX(Nidos_activos_por_visita) IS NULL THEN 'NA'
    ELSE MAX(Nidos_activos_por_visita)
  END Nidos_activos_por_visita,
  CASE
    WHEN Notas IS NULL THEN 'NA'
    ELSE Notas
  END Notas
FROM ${table_name}
GROUP BY Isla, Intervalo
" ${data_file} 