#!/usr/bin/env bash

INPUT_FILE_PATH="$1"
OUTPUT_FILE_PATH="$2"

csvsql --snifflimit 0 --no-inference --blanks --query \
    "SELECT Nombre_en_ingles AS Especie, \
      COUNT(DISTINCT Isla) AS num_isla \
    FROM csvSubsetBurrowsData \
    GROUP BY Nombre_en_ingles " \
${INPUT_FILE_PATH} > t1.csv

csvsql --snifflimit 0 --no-inference --blanks --query \
    "SELECT Nombre_en_ingles, \
      COUNT(DISTINCT Isla) AS num_islas, \
      Temporada, \
      SUM(Maxima_cantidad_nidos) AS Maxima_cantidad_nidos \
    FROM csvSubsetBurrowsData \
    GROUP BY Nombre_en_ingles, Temporada " \
${INPUT_FILE_PATH} > t2.csv

csvsql --snifflimit 0 --no-inference --blanks --query \
    "SELECT Especie, t2.Temporada,t2.Maxima_cantidad_nidos \
     FROM t1 \
     INNER JOIN t2 ON \
     t1.Especie = t2.Nombre_en_ingles AND t1.num_isla = t2.num_islas\
" \
t1.csv t2.csv > ${OUTPUT_FILE_PATH}

rm t1.csv
rm t2.csv


