#!/usr/bin/env bash
#
ARCHIVO_DE_DATOS=$1
NOMBRE_TABLA=$(basename "$ARCHIVO_DE_DATOS" .csv)
NOMBRE_ISLA=$2
csvsql --query \
    "SELECT Isla, Intervalo, \
        CASE \
          WHEN MAX(Nidos_activos_por_visita) IS NULL THEN 'NA' \
          ELSE MAX(Nidos_activos_por_visita) \
        END Nidos_activos_por_visita \
    FROM $NOMBRE_TABLA \
    WHERE Isla = '$NOMBRE_ISLA' \
    GROUP BY Intervalo " \
$ARCHIVO_DE_DATOS 