#!/usr/bin/env bash
#
DATA_FILE=$1
TABLE_NAME=$(basename "$DATA_FILE" .csv)
ISLET_NAME=$2
csvsql --query \
    "SELECT Isla, Intervalo, \
        CASE \
          WHEN MAX(Nidos_activos_por_visita) IS NULL THEN 'NA' \
          ELSE MAX(Nidos_activos_por_visita) \
        END Nidos_activos_por_visita, \
        CASE \
          WHEN Notas IS NULL THEN 'NA' \
          ELSE Notas \
        END Notas \
    FROM ${TABLE_NAME} \
    GROUP BY Isla, Intervalo" \
${DATA_FILE} 