#!/usr/bin/env bash
#
data_file=$1
sql_query=$2
export table_name=$(basename "$data_file" .csv)
src_path=$(dirname "${0}")
query=$(envsubst < ${src_path}/${sql_query})
csvsql --query "
$query
" ${data_file} 