#!/usr/bin/env python
#
# join_cormorant_growth_rates une resultados de islas del pacífico e 
# islas de sinaloa.

import matplotlib

matplotlib.use("Agg")

from cli_paths import path_files
from matplotlib.ticker import MaxNLocator
from bootstraping_tools import *

import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

path = path_files()

pacific_data = path.input[0][0]
patos_data = path.input[1][0]
pajaros_data = path.input[2][0]
alcatraz_data = path.input[3][0]
result_table = path.output[0][0]

pacific_table = pd.read_csv(pacific_data)
patos_distribution = pd.read_csv(patos_data)
pajaros_distribution = pd.read_csv(pajaros_data)
alcatraz_distribution = pd.read_csv(alcatraz_data)

interval_patos = get_bootstrap_interval(np.percentile(patos_distribution["Tasa de crecimiento"], [2.5, 50, 97.5]))
interval_pajaros = get_bootstrap_interval(np.percentile(pajaros_distribution["Tasa de crecimiento"], [2.5, 50, 97.5]))
interval_alcatraz = get_bootstrap_interval(np.percentile(alcatraz_distribution["Tasa de crecimiento"], [2.5, 50, 97.5]))

patos_dic = {"Isla": "Patos", "Tasa_de_crecimiento": f"${{{interval_patos[1]}}}_{{-{interval_patos[0]}}}^{{+{interval_patos[2]}}}$"}
pajaros_dic = {"Isla": "Pajaros", "Tasa_de_crecimiento": f"${{{interval_pajaros[1]}}}_{{-{interval_pajaros[0]}}}^{{+{interval_pajaros[2]}}}$"}
alcatraz_dic = {"Isla": "Alcatraz", "Tasa_de_crecimiento": f"${{{interval_alcatraz[1]}}}_{{-{interval_alcatraz[0]}}}^{{+{interval_alcatraz[2]}}}$"}

data_subset = pacific_table[['Isla', 'Tasa_de_crecimiento']]

data_subset = data_subset.append(patos_dic,ignore_index=True)
data_subset = data_subset.append(pajaros_dic,ignore_index=True)
data_subset = data_subset.append(alcatraz_dic,ignore_index=True).sort_values(by="Isla")

data_subset = data_subset.rename(columns={"Tasa_de_crecimiento": "Tasa de crecimiento"})
data_subset.to_csv(result_table, index=False)

