#!/usr/bin/env bash
#
DATA_FILE=${1}
TABLE_NAME=$(basename "$DATA_FILE" .csv)
P_VALUE_COLUMN=${2}
csvsql -y 0 -I --blanks --query \
    "SELECT 
      Especie,
      Isla,
      Tasa_de_crecimiento AS 'Tasa de crecimiento',
      ${P_VALUE_COLUMN} AS 'p-valor'
    FROM ${TABLE_NAME}
    WHERE ${P_VALUE_COLUMN} <= 0.1" \
${DATA_FILE}