#!/usr/bin/env bash
#
data_file=${1}
table_name=$(basename "${data_file}" .csv)
p_value_column=${2}
conditional=${3}
csvsql --snifflimit 0 --no-inference --blanks --query "
SELECT 
  Islet AS 'Archipelago/Island',
  Growth_rate AS 'Growth rate',
  CASE
    WHEN ${p_value_column} < 0.001
    THEN '$<0.001$'
    ELSE ${p_value_column}
  END 'p-value'
FROM ${table_name}
WHERE ${p_value_column} ${conditional}
" ${data_file}