#!/usr/bin/env bash
#
# Este query selecciona la tasa de crecimiento poblacional y el p-valor de las tablas de tasas de
# crecimiento por isla.

data_file=${1}
p_value_column=${2}
conditional=${3}
field_option=1

select_growth_rates_and_p_values ${data_file} ${p_value_column} "${conditional}" ${field_option}