name: Conservación de Islas
on: [push, pull_request]
jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci .
    - name: Corre pruebas
      run: docker run islasgeci make coverage
    - name: Ejecuta objetivo principal del Makefile
      run: docker run islasgeci make
    - name: Verifica el formato
      run: docker run islasgeci make check
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci make mutants
